#!/usr/bin/env python3
"""
phase5_generate.py
==================
PHASE 5 (Tier 1) — Scaffold-constrained generation + multi-objective drug-likeness
scoring for novel Papulacandin-class FKS1 inhibitors.

WHAT THIS DOES (and why it is honest for limited data)
------------------------------------------------------
The validated SAR handle in the fusacandin series is the AROMATIC C-6' ester
(the position Yeung 1996 varied). We therefore:
  1. Extract the conserved papulacandin/fusacandin CORE from a serum-tolerant
     lead by cleaving its aromatic C-6' ester (chemistry verified by InChIKey
     round-trip).
  2. Build an ACYL fragment library = (a) data-derived acyls harvested from the
     real analogs + (b) DESIGNED acyls encoding the two design axes from
     Phase 1/4: rigid aromatic (Axis 1) and rigid-aromatic + polar/cationic
     handle (Axis 2).
  3. Re-esterify the core with every acyl -> a virtual library of novel analogs.
  4. Score each with a transparent multi-objective function (NO fragile learned
     activity predictor): QED drug-likeness, synthetic accessibility, the
     Phase-1 design-rule score, and novelty vs known compounds.
  5. RETROSPECTIVELY VALIDATE: the known analogs are regenerated by this process;
     we check the design-rule score tracks their observed serum MIC.
  6. Emit the top candidates as 3D SDF ready for CREST/xTB conformer ensembles
     (Tier-4 QM funnel) and a CREST command template.

NOTE ON DRUG-LIKENESS: papulacandins are large glycolipids in "beyond-Rule-of-5"
(bRo5) space, so absolute Lipinski compliance is meaningless. We use QED/Ro5 as
RELATIVE within-chemotype rankings, which is the appropriate framing and itself
a finding for the drug-likeness study.

Outputs (analysis/outputs/):
  * phase5_virtual_library.csv      — all generated analogs + scores
  * phase5_top_candidates.sdf       — 3D structures of top N (CREST-ready)
  * phase5_crest_commands.sh        — per-candidate CREST/xTB command template
  * phase5_retrospective.png        — design-rule score vs observed serum MIC
  * phase5_score_distributions.png  — drug-likeness/SA/novelty of the library
"""
from __future__ import annotations
import os
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats

from rdkit import Chem
from rdkit.Chem import QED, AllChem, Descriptors, rdMolDescriptors, DataStructs
from rdkit.Chem import rdFingerprintGenerator
from rdkit import RDLogger
RDLogger.DisableLog("rdApp.*")

# SA score from RDKit contrib
from rdkit.Chem import RDConfig
sys.path.append(os.path.join(RDConfig.RDContribDir, "SA_Score"))
import sascorer  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CORE = os.path.join(ROOT, "curated", "core_tables")
OUT = os.path.join(HERE, "outputs")
os.makedirs(OUT, exist_ok=True)
plt.rcParams.update({"figure.dpi": 130, "font.size": 10,
                     "axes.spines.top": False, "axes.spines.right": False})

TOP_N_FOR_QM = 12
AROM_ESTER = Chem.MolFromSmarts("[O;X2:1][C:2](=O)[c:3]")
_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

# ==========================================================================
# Core extraction (verified chemistry) and re-esterification
# ==========================================================================
def split_aromatic_ester(mol):
    """Cleave the aromatic C-6' ester; return (core_with_dummy, acyl_with_dummy)."""
    m = mol.GetSubstructMatch(AROM_ESTER)
    if not m:
        return None, None
    oxy, carb = m[0], m[1]
    rw = Chem.RWMol(mol)
    bidx = rw.GetBondBetweenAtoms(oxy, carb).GetIdx()
    frag = Chem.FragmentOnBonds(rw, [bidx], addDummies=True)
    parts = Chem.GetMolFrags(frag, asMols=True, sanitizeFrags=True)
    if len(parts) != 2:
        return None, None
    core = max(parts, key=lambda p: p.GetNumAtoms())
    acyl = min(parts, key=lambda p: p.GetNumAtoms())
    for p in (core, acyl):
        for a in p.GetAtoms():
            if a.GetAtomicNum() == 0:
                a.SetAtomMapNum(1)
    return core, acyl

def attach(core, acyl):
    try:
        m = Chem.molzip(core, acyl)
        Chem.SanitizeMol(m)
        return m
    except Exception:
        return None

# ==========================================================================
# Scoring (transparent, no learned activity predictor)
# ==========================================================================
def ecfp(mol):
    return _gen.GetFingerprint(mol)

_POLAR_PATTERNS = [Chem.MolFromSmarts(s) for s in (
    "[OX2H]",            # hydroxyl
    "[NX3;!$(N=*);!$(N-C=O)]",  # amine
    "[CX3](=O)[OX2H1]",  # carboxylic acid
    "[CX3](=O)[NX3]",    # amide
    "[#7+]",             # cationic N
    "[SX4](=O)(=O)[NX3]",  # sulfonamide
    "[nX2]",             # aromatic N (pyridine-type)
)]

def design_rule_score(acyl_mol):
    """Phase-1/4 design rules on the variable acyl group:
       reward aromatic rings (rigidity, Axis 1), reward a polar/H-bond handle
       (Axis 2), penalize rotatable bonds (flexibility)."""
    n_arom = rdMolDescriptors.CalcNumAromaticRings(acyl_mol)
    n_rot = rdMolDescriptors.CalcNumRotatableBonds(acyl_mol)
    has_polar = any(acyl_mol.HasSubstructMatch(p) for p in _POLAR_PATTERNS)
    s = 0.30 * min(n_arom, 3) / 3 + 0.30 * (1 if has_polar else 0) \
        + 0.40 * np.exp(-n_rot / 4.0)
    return round(s, 3), n_arom, n_rot, bool(has_polar)

def score_molecule(full_mol, acyl_mol, known_fps):
    qed = QED.qed(full_mol)
    sa = sascorer.calculateScore(full_mol)           # 1 easy .. 10 hard
    sa_norm = (10 - sa) / 9.0
    drule, n_arom, n_rot, polar = design_rule_score(acyl_mol)
    # novelty: 1 - max Tanimoto to known curated compounds
    fp = ecfp(full_mol)
    sims = DataStructs.BulkTanimotoSimilarity(fp, known_fps)
    novelty = 1.0 - max(sims) if sims else 1.0
    ro5_viol = rdMolDescriptors.CalcNumLipinskiHBA(full_mol) > 10 \
        or rdMolDescriptors.CalcNumLipinskiHBD(full_mol) > 5 \
        or Descriptors.MolWt(full_mol) > 500 \
        or Descriptors.MolLogP(full_mol) > 5
    combined = round(0.30 * qed + 0.20 * sa_norm + 0.35 * drule + 0.15 * novelty, 4)
    return dict(qed=round(qed, 3), sa_score=round(sa, 2), sa_norm=round(sa_norm, 3),
                design_rule_score=drule, n_aromatic_rings_acyl=n_arom,
                n_rotbond_acyl=n_rot, acyl_has_polar=polar,
                novelty=round(novelty, 3), mw=round(Descriptors.MolWt(full_mol), 1),
                clogp=round(Descriptors.MolLogP(full_mol), 2),
                ro5_pass=not ro5_viol, combined_score=combined)

# ==========================================================================
# Load data; build known-compound fingerprints; harvest data-derived acyls
# ==========================================================================
cm = pd.read_csv(os.path.join(CORE, "compounds_master.csv"))
pairs = pd.read_csv(os.path.join(OUT, "serum_gap_pairs.csv"))

known_mols, known_fps = [], []
for smi in cm["smiles_canonical"].dropna():
    m = Chem.MolFromSmiles(smi)
    if m:
        known_mols.append(m)
        known_fps.append(ecfp(m))

# Template core = from a serum-tolerant lead (PAPU-0080, 6j; serum MIC 12.5).
tmpl = Chem.MolFromSmiles(cm.set_index("compound_id").loc["PAPU-0080", "smiles_canonical"])
core, _ = split_aromatic_ester(tmpl)
assert core is not None, "core extraction failed"

# (a) data-derived acyls from every analog bearing an aromatic C-6' ester
acyl_lib = {}   # name -> acyl mol (with dummy)
for _, r in cm.iterrows():
    smi = r["smiles_canonical"]
    if not isinstance(smi, str):
        continue
    m = Chem.MolFromSmiles(smi)
    if m is None:
        continue
    c, ac = split_aromatic_ester(m)
    if ac is not None and 6 <= ac.GetNumAtoms() <= 40:
        acyl_lib[f"data::{r['compound_id']}"] = ac

# (b) designed acyls: rigid aromatic (Axis 1) + rigid-aromatic+polar (Axis 2)
designed = {
    "design::biphenyl": "[*:1]C(=O)c1ccc(-c2ccccc2)cc1",
    "design::biphenyl_4COOH": "[*:1]C(=O)c1ccc(-c2ccc(C(=O)O)cc2)cc1",
    "design::biphenyl_4CONH2": "[*:1]C(=O)c1ccc(-c2ccc(C(N)=O)cc2)cc1",
    "design::biphenyl_4morpholine": "[*:1]C(=O)c1ccc(-c2ccc(N3CCOCC3)cc2)cc1",
    "design::biphenyl_4OH": "[*:1]C(=O)c1ccc(-c2ccc(O)cc2)cc1",
    "design::biphenyl_4NH2": "[*:1]C(=O)c1ccc(-c2ccc(N)cc2)cc1",
    "design::naphthoyl": "[*:1]C(=O)c1ccc2ccccc2c1",
    "design::naphthoyl_6OH": "[*:1]C(=O)c1ccc2cc(O)ccc2c1",
    "design::pyridylphenyl": "[*:1]C(=O)c1ccc(-c2ccncc2)cc1",
    "design::biphenyl_4CH2NMe2": "[*:1]C(=O)c1ccc(-c2ccc(CN(C)C)cc2)cc1",
    "design::quinolinecarbonyl": "[*:1]C(=O)c1ccc2ncccc2c1",
    "design::biphenyl_4SO2NH2": "[*:1]C(=O)c1ccc(-c2ccc(S(N)(=O)=O)cc2)cc1",
}
for name, asmi in designed.items():
    am = Chem.MolFromSmiles(asmi)
    if am:
        for a in am.GetAtoms():
            if a.GetAtomicNum() == 0:
                a.SetAtomMapNum(1)
        acyl_lib[name] = am

# ==========================================================================
# Enumerate library, dedupe, score
# ==========================================================================
seen, rows, mol_by_key = set(), [], {}
for aname, acyl in acyl_lib.items():
    full = attach(core, acyl)
    if full is None:
        continue
    ik = Chem.MolToInchiKey(full)
    if ik in seen:
        continue
    seen.add(ik)
    sc = score_molecule(full, acyl, known_fps)
    sc.update(acyl_source=aname.split("::")[0], acyl_name=aname.split("::")[1],
              inchikey=ik, smiles=Chem.MolToSmiles(full))
    rows.append(sc)
    mol_by_key[ik] = full

lib = pd.DataFrame(rows).sort_values("combined_score", ascending=False).reset_index(drop=True)
# Map regenerated knowns back to their PAPU id (for retrospective validation)
known_ik = {Chem.MolToInchiKey(m): cid for m, cid in
            zip(known_mols, cm["compound_id"])}
lib["matches_known_compound"] = lib["inchikey"].map(known_ik).fillna("")
lib["is_novel"] = lib["matches_known_compound"] == ""
lib.to_csv(os.path.join(OUT, "phase5_virtual_library.csv"), index=False)

# ==========================================================================
# Retrospective validation: design-rule score vs observed serum MIC
# ==========================================================================
def parse_mic(s):
    s = str(s).strip()
    for r in (">=", "<=", ">", "<", "="):
        if s.startswith(r):
            s = s[len(r):]
            break
    try:
        return float(s)
    except ValueError:
        return np.nan

pairs["serum_mic_num"] = pairs["serum_mic_ugml"].apply(parse_mic)
val = lib[lib["matches_known_compound"] != ""].merge(
    pairs[["compound_id", "serum_mic_num"]],
    left_on="matches_known_compound", right_on="compound_id")
rho, pval = (stats.spearmanr(val["design_rule_score"], np.log10(val["serum_mic_num"]))
             if len(val) >= 4 else (np.nan, np.nan))

fig, ax = plt.subplots(figsize=(5.8, 4.6))
ax.scatter(val["design_rule_score"], val["serum_mic_num"], s=55,
           color="#264653", edgecolor="k", linewidth=0.3)
ax.set_yscale("log")
ax.set_xlabel("Design-rule score (higher = more rigid-aromatic + polar)")
ax.set_ylabel("Observed serum MIC (ug/mL, log)")
ax.set_title(f"Phase 5 retrospective: design rules vs serum MIC\n"
             f"Spearman rho={rho:.2f} (n={len(val)}) — negative = rules work")
fig.tight_layout()
fig.savefig(os.path.join(OUT, "phase5_retrospective.png"))
plt.close(fig)

# ==========================================================================
# Library property distributions (drug-likeness study)
# ==========================================================================
fig, axes = plt.subplots(1, 3, figsize=(11, 3.6))
for ax, col, title in zip(axes, ["qed", "sa_score", "novelty"],
                          ["QED drug-likeness", "Synthetic accessibility (low=easy)", "Novelty vs known"]):
    ax.hist(lib[col], bins=15, color="#2a9d8f", edgecolor="white")
    ax.set_title(title); ax.set_xlabel(col)
fig.suptitle("Phase 5: virtual library property distributions (bRo5 chemotype)")
fig.tight_layout()
fig.savefig(os.path.join(OUT, "phase5_score_distributions.png"))
plt.close(fig)

# ==========================================================================
# Emit top NOVEL candidates as 3D SDF (CREST-ready) + CREST command template
# ==========================================================================
top = lib[lib["is_novel"]].head(TOP_N_FOR_QM)
writer = Chem.SDWriter(os.path.join(OUT, "phase5_top_candidates.sdf"))
crest_cmds = ["#!/bin/bash",
              "# CREST conformer ensembles for top Phase-5 candidates (run on QM infra).",
              "# Requires xtb + crest. Papulacandins are highly flexible -> ensembles matter.",
              "# Suggested: GFN2-xTB, implicit water (alpb), to compare exposed hydrophobic SASA.", ""]
for i, (_, r) in enumerate(top.iterrows(), 1):
    m = Chem.AddHs(mol_by_key[r["inchikey"]])
    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    params.useMacrocycleTorsions = True
    # Large, flexible glycolipids often fail standard embedding; fall back to
    # random-coordinate initialization, which reliably embeds this chemotype.
    ok = AllChem.EmbedMolecule(m, params)
    if ok != 0:
        params.useRandomCoords = True
        params.maxIterations = 2000
        ok = AllChem.EmbedMolecule(m, params)
    if ok == 0:
        AllChem.MMFFOptimizeMolecule(m, maxIters=500)
        m.SetProp("_Name", f"cand{i:02d}_{r['acyl_name']}")
        m.SetProp("combined_score", str(r["combined_score"]))
        writer.write(m)
        crest_cmds.append(
            f"crest cand{i:02d}_{r['acyl_name']}.xyz --gfn2 --alpb water "
            f"--T 8 > cand{i:02d}.out   # score={r['combined_score']}")
writer.close()
with open(os.path.join(OUT, "phase5_crest_commands.sh"), "w") as fh:
    fh.write("\n".join(crest_cmds) + "\n")

# ==========================================================================
# Console summary
# ==========================================================================
print("PHASE 5 (Tier 1) — scaffold-constrained generation + scoring")
print("=" * 62)
print(f"Acyl fragments: {len(acyl_lib)} ({sum(1 for k in acyl_lib if k.startswith('data'))} data-derived, "
      f"{sum(1 for k in acyl_lib if k.startswith('design'))} designed)")
print(f"Unique analogs generated: {len(lib)}  (novel: {lib['is_novel'].sum()})")
print(f"Retrospective design-rule vs serum MIC: Spearman rho={rho:.2f} (p={pval:.3f}, n={len(val)})")
print(f"\nTop novel candidates (CREST-ready, written to SDF):")
cols = ["acyl_name", "combined_score", "qed", "sa_score", "design_rule_score", "novelty", "mw"]
print(top[cols].to_string(index=False))
print(f"\nWrote: phase5_virtual_library.csv, phase5_top_candidates.sdf,")
print(f"       phase5_crest_commands.sh, phase5_retrospective.png, phase5_score_distributions.png")
